In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [45]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([1, 'female', 38.0, 1, 0, 71.5, 'C'],dtype=object).reshape(1,7)

In [46]:
test_input

array([[1, 'female', 38.0, 1, 0, 71.5, 'C']], dtype=object)

In [47]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Python\General_Python\.venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [48]:
test_input_sex

array([[1., 0.]])

In [49]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [50]:
test_input_embarked

array([[1., 0., 0.]])

In [51]:
test_input_age = test_input[:,2].reshape(1,1)

In [52]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [53]:
test_input_transformed.shape

(1, 10)

In [54]:
clf.predict(test_input_transformed)

array([1], dtype=int64)